Update infrastructure.yml

diff --git a/.github/workflows/infrastructure.yml b/.github/workflows/infrastructure.yml
--- a/.github/workflows/infrastructure.yml
+++ b/.github/workflows/infrastructure.yml
@@ -51,6 +51,39 @@ jobs:
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         aws-region: eu-north-1
 
+    - name: Install TFLint
+      run: |
+          TFLINT_VERSION="v0.55.0"
+          curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
+          
+          if [ ! -s "tflint.zip" ]; then
+            echo "Error: Downloaded TFLint archive is empty or invalid."
+            exit 1
+          fi
+
+          unzip tflint.zip
+          chmod +x tflint
+          sudo mv tflint /usr/local/bin/
+          rm tflint.zip
+          
+          echo "TFLint installed successfully:"
+          tflint --version
+
+
+      # Step: Run TFLint
+    - name: Run TFLint
+      run: |
+         cd environments/${{ github.event.inputs.environment || 'dev' }}
+
+         # Ensure .tflint.hcl exists
+         if [ ! -f ".tflint.hcl" ]; then
+            cat <<EOF > .tflint.hcl
+            plugin "terraform" {
+            enabled = true
+           }
+         EOF
+         fi
+
     - name: Initialize Terraform
       run: |
         cd environments/${{ github.event.inputs.environment }}
